**Create DataFrame**

In [3]:
import pandas as pd

In [4]:
rows = [
    ['Paul', 32, 'Software Engineer'],
    ['Sarah', 28, 'Data Scientist'],
    ['Stanley',9 , 'Dog']
    ]

pd.DataFrame(rows)

         0   1                  2
0     Paul  32  Software Engineer
1    Sarah  28     Data Scientist
2  Stanley   9                Dog

**Add columns and row labels with index and columns arguments**

In [5]:
pd.DataFrame(rows, 
             columns=['Name', 'Age', 'Occupation'],
             index=['row1', 'row2', 'row3'])

         Name  Age         Occupation
row1     Paul   32  Software Engineer
row2    Sarah   28     Data Scientist
row3  Stanley    9                Dog

**Using a dictionary to specify the column labels**

In [10]:
family_dict = {'Name': ['Paul', 'Sarah', 'Stanley'],
               'Age': [32, 28, 9],
               'Occupation': ['Software Engineer', 'Data Scientist', 'Dog']}
pd.DataFrame(family_dict)

      Name  Age         Occupation
0     Paul   32  Software Engineer
1    Sarah   28     Data Scientist
2  Stanley    9                Dog

In [13]:
df = pd.DataFrame(family_dict)
df.columns = ['days since getting a full night\'s sleep', 'Name','dream job']
df.index=['a', 'b', 'c']

df

  days since getting a full night's sleep  Name          dream job
a                                    Paul    32  Software Engineer
b                                   Sarah    28     Data Scientist
c                                 Stanley     9                Dog