In [1]:
import pandas as pd

**Method1 : Convert dictionary to pandas df**

In [2]:
 my_dict = {
    'college':['Columbia','Stanford','Harvard','IIT'],
    'accepted':[True,False,True,False]
 }

 #Convert dict to dataframe
 my_df = pd.DataFrame(my_dict)
 my_df

    college  accepted
0  Columbia      True
1  Stanford     False
2   Harvard      True
3       IIT     False

**Method 2 : Create a DataFrame from list of lists**

In [3]:
list_of_lists = [['Columbia',True],['Stanford',False],['IIT',False]]

my_df = pd.DataFrame(list_of_lists , columns= ['college','accepted'])
my_df

    college  accepted
0  Columbia      True
1  Stanford     False
2       IIT     False

**Method 3 : Create a DataFrame from .csv**

In [19]:
social = pd.read_csv("PewDataCSV.csv")

In [20]:
social

,respid,sample,comp,int_date,lang,state,density,usr,qs1,sex,...,income,party,partyln,hh1,hh3,ql1,ql1a,qc1,weight,cellweight
0,798,1,1,1/26/2021,1,51,5,S,,2,...,6,2,,1,,1,,,0.557187,
1,1017,1,1,1/25/2021,1,39,2,S,,1,...,5,1,,2,2,1,,,0.987209,
2,1181,1,1,1/25/2021,1,32,2,U,,2,...,8,3,2,2,2,1,,,0.925147,
3,1388,1,1,1/25/2021,1,4,3,U,,1,...,8,2,,1,,1,,,0.311080,
4,1664,1,1,1/26/2021,1,12,2,S,,2,...,7,2,,2,2,1,,,0.396548,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1497,310017,2,1,2/3/2021,2,24,4,S,2,1,...,6,3,2,8,2,,,1,1.017624,.8914809
1498,310930,2,1,2/4/2021,2,35,1,R,2,1,...,2,3,2,3,3,,,2,1.312498,1.179117
1499,310960,2,1,2/4/2021,2,41,2,S,2,1,...,7,1,,5,3,,,2,0.786633,.695447
1500,311118,2,1,2/4/2021,2,6,3,U,2,2,...,4,3,8,4,4,,,1,2.203869,1.698473
1501,311426,2,1,2/4/2021,2,6,1,U,2,1,...,4,2,,5,4,,,2,2.459681,2.2229945

In [26]:
#slicing with square brackets
social[['weight','respid']]

        weight  respid
0     0.557187     798
1     0.987209    1017
2     0.925147    1181
3     0.311080    1388
4     0.396548    1664
...        ...     ...
1497  1.017624  310017
1498  1.312498  310930
1499  0.786633  310960
1500  2.203869  311118
1501  2.459681  311426

[1502 rows x 2 columns]

In [28]:
social[0:5]

,respid,sample,comp,int_date,lang,state,density,usr,qs1,sex,...,income,party,partyln,hh1,hh3,ql1,ql1a,qc1,weight,cellweight
0,798,1,1,1/26/2021,1,51,5,S,,2,...,6,2,,1,,1,,,0.557187,
1,1017,1,1,1/25/2021,1,39,2,S,,1,...,5,1,,2,2,1,,,0.987209,
2,1181,1,1,1/25/2021,1,32,2,U,,2,...,8,3,2,2,2,1,,,0.925147,
3,1388,1,1,1/25/2021,1,4,3,U,,1,...,8,2,,1,,1,,,0.311080,
4,1664,1,1,1/26/2021,1,12,2,S,,2,...,7,2,,2,2,1,,,0.396548,

In [32]:
#slicing with loc
social.loc[:,'respid':'state']

      respid  sample  comp   int_date  lang  state
0        798       1     1  1/26/2021     1     51
1       1017       1     1  1/25/2021     1     39
2       1181       1     1  1/25/2021     1     32
3       1388       1     1  1/25/2021     1      4
4       1664       1     1  1/26/2021     1     12
...      ...     ...   ...        ...   ...    ...
1497  310017       2     1   2/3/2021     2     24
1498  310930       2     1   2/4/2021     2     35
1499  310960       2     1   2/4/2021     2     41
1500  311118       2     1   2/4/2021     2      6
1501  311426       2     1   2/4/2021     2      6

[1502 rows x 6 columns]

In [38]:
social.iloc[:,1]

0       1
1       1
2       1
3       1
4       1
       ..
1497    2
1498    2
1499    2
1500    2
1501    2
Name: sample, Length: 1502, dtype: int64

In [39]:
incomeunder5 = social['income']<5

In [40]:
social[incomeunder5]

,respid,sample,comp,int_date,lang,state,density,usr,qs1,sex,...,income,party,partyln,hh1,hh3,ql1,ql1a,qc1,weight,cellweight
7,3010,1,1,2/2/2021,1,6,2,U,,1,...,3,1,,1,,2,,,0.311080,
8,3015,1,1,1/26/2021,1,9,4,S,,2,...,3,3,1,2,2,1,,,1.777680,
13,5707,1,1,1/25/2021,1,35,1,U,,2,...,4,3,9,1,,1,,,0.311080,
15,6126,1,1,2/1/2021,1,29,1,R,,2,...,3,3,8,2,2,1,,,1.451820,
18,7104,1,1,1/26/2021,1,36,2,R,,2,...,3,3,1,3,3,1,,,2.298055,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1494,309768,2,1,2/3/2021,2,48,5,S,2,2,...,3,3,8,4,4,,,2,2.459681,2.2723671
1496,309974,2,1,2/3/2021,2,6,2,S,2,2,...,3,2,,1,,,,2,0.679927,1.1209539
1498,310930,2,1,2/4/2021,2,35,1,R,2,1,...,2,3,2,3,3,,,2,1.312498,1.179117
1500,311118,2,1,2/4/2021,2,6,3,U,2,2,...,4,3,8,4,4,,,1,2.203869,1.698473
1501,311426,2,1,2/4/2021,2,6,1,U,2,1,...,4,2,,5,4,,,2,2.459681,2.2229945